### ISSUE TITLE
Add latest versions of dependencies to remove error

### ISSUE THREAD

**Issue by harshalmittal4** [chaoss/grimoirelab-manuscripts#125]
Hey @valeriocos , 
The problem still persists when I use the command
`p2o.py --enrich --index perceval_git_raw --index-enrich perceval_git -e http://localhost:9200 --no_inc --debug --db-host 127.0.0.1 --db-sortinghat sortinghatDB --db-user root git https://github.com/chaoss/grimoirelab-perceval`
to generate index for `git ` date source. I was doing this for generating the report. 
It is using grimoire-elk==0.36.0.

_Originally posted by @harshalmittal4 in https://github.com/chaoss/grimoirelab-elk/issues/574#issuecomment-474216616_

**Comment by valeriocos** [comment]
Please @harshalmittal4 try with the latest version of ELK or the code in the master branch.
Thanks!

**Comment by harshalmittal4** [comment]
Hi, it is running fine with the latest version of grimoire-elk, could we update it in setup.py?
Sorry to bother you for this.

**Comment by valeriocos** [comment]
sure, feel free to open a PR. Thanks

**Comment by harshalmittal4** [comment]
Hey @valeriocos, I was wondering how to include the latest version (pre-release) in setup.py in the PR.
(I managed to run it by manually cloning grimoire-elk and perceval-finos repositories and installing them) 

Shall it be included in requirements.txt. What would be helpful?

**Comment by harshalmittal4** [comment]
Shall I add it to requirements.txt?

**Comment by valeriocos** [comment]
Sure, you can do something like this: https://github.com/chaoss/grimoirelab-sirmordred/blob/master/requirements.txt

For the setup.py, it won't work since there isn't a new package in pypi (https://pypi.org/project/grimoire-elk/#history). However, I would ask @jgbarah that can give a better answer about it.

**Comment by harshalmittal4** [comment]
Thanks @valeriocos for clarifying, I was bit unsure regarding it couldn't be done with setup.py.
@jgbarah kindly see.

**Comment by harshalmittal4** [comment]
@valeriocos @jgbarah ping.

**Comment by valeriocos** [comment]
Hi @harshalmittal4 , if I'm not wrong a new community release should be out. @jgbarah can confirm

**Comment by harshalmittal4** [comment]
Yes, you're right @valeriocos. I just checked it by installing again in a new virtualenv, so seems like there is no need for this now :sweat_smile:

**Comment by valeriocos** [comment]
you're welcome @harshalmittal4 :)

**Comment by valeriocos** [comment]
feel free to close this issue
