### ISSUE TITLE
Make git the name of the enriched index for git

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab-manuscripts#17]
AFAIK, by default Mordred is creating the alias for the git enriched index as `git`. However, it seems Manuscripts is looking for `git_enrich` (see #16). Could somebody more knowledgeable on Manuscripts confirm this, so that we keep this issue open, or deny, and we just close it?

**Comment by aswanipranjal** [comment]
Hey @jgbarah, that might be because in [report.py](https://github.com/chaoss/grimoirelab-manuscripts/blob/master/manuscripts/report.py), the `GIT_INDEX` variable has been set as `git_enrich`.

**Comment by jgbarah** [comment]
Yes, I think so. Feel free to submit a pull request fixing that!

**Comment by aswanipranjal** [comment]
@jgbarah, I had a question: should we allow the user to choose the indices that they want to create a report on? Hard coding the enriched index name to `git` won't allow us to store data from multiple repositories as all of them cannot be named `git`. We can instead add name of the index to be analysed, as a parameter to the manuscripts command.

**Comment by jgbarah** [comment]
I think we should, by default, use the same indexes (index aliases, in fact) that the dashboard uses. That's git for git (instead of git_enrich). Same for other datasources.

In addition to that, yes, it would be nice letting the user to override this name. Currently that can be done via the mordred.cfg file, but it would be much better having also command line options. I'm opening a separate issue for that.
