### ISSUE TITLE
Let users decide the name of an index for each data source

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab-manuscripts#21]
Now, the name of the index for each supported data source is wired in the code. It would be better if that wiring acted just as a default name, that the user can override via command line options. Pull requests with that aim are welcome.

**Comment by aswanipranjal** [comment]
@jgbarah I'll get started on this.

**Comment by jaishreedhage** [comment]
@jgbarah @aswanipranjal  Hi, is this issue currently being worked on? I wanted to work on this. Please let me know. Thanks.

**Comment by aswanipranjal** [comment]
Hey @jaishreedhage, yes I am currently working on this issue.
