### ISSUE TITLE
The data and figs for the report creation are copied recursively

### ISSUE THREAD

**Issue by acs** [chaoss/grimoirelab-manuscripts#24]
In each generation of a report the data and figs folders used to create the PDF report file are copied recursively. For example:

```
(acs@dellx) (quarters-titles % u=) ~/devel/grimoirelab-manuscripts-fork-acs $ ls -l bitergia-servers/opnfv/report_data/figs/figs/data/figs/data
total 804
drwxrwxr-x 2 acs acs   4096 mar  1 14:40 activity
....
```

**Comment by f2014169** [comment]
@jgbarah  shall i take this? I figured out the bug

**Comment by jgbarah** [comment]
@f2014169 go ahead if you feel like that...

**Comment by f2014169** [comment]
@acs @jgbarah  please visit https://github.com/chaoss/grimoirelab-manuscripts/pull/30

**Comment by acs** [comment]
> @acs @jgbarah please visit #30

Hmm, it is not clear for me what to do in #30. Please. to work in this bug open a specific PR that address it. Thanks you @f2014169

**Comment by jgbarah** [comment]
@acs: #30 is about a different stuff, explained in that pr. Please, add your review there if you don't mind.

**Comment by acs** [comment]
> @acs: #30 is about a different stuff, explained in that pr. Please, add your review there if you don't mind.

Yes, I know it, but I need to find what change about all of them is related to this issue. And after the review, the code can not be merged from there if we want a clean merge.

If it is not possible to get the commit related to this issue #24 and create a PR specific for it, I would try to do the review in #30. Could you specify which is the specific commit in #30?  I suppose it is: https://github.com/chaoss/grimoirelab-manuscripts/pull/30#issue-172606061 but I can not find code fixing current issue #24.

**Comment by jgbarah** [comment]
I see now. It seems #30 includes code for both the logo stuff, and the recursive copy stuff. I've found the code for the latter in it, and reviewed it asking to be moved to a new pull request. Thanks, @acs.

**Comment by f2014169** [comment]
@acs  @jgbarah  i've removed code for #24 from #30 ,ill create seperate pull request

**Comment by Prabhat-IIT** [comment]
@acs  @jgbarah  please review my opened pr once you get some time :)
