### ISSUE TITLE
URL and Latex error

### ISSUE THREAD

**Issue by Prabhat-IIT** [chaoss/grimoirelab-manuscripts#34]
When I tried the command `manuscripts -d /tmp/reports -u http://localhost:9200    -n GrimoireLab --data-sources git` 
I encountered an error:

> Traceback (most recent call last):
  File "/home/prabhat/venvs/grimoirelab/bin/manuscripts", line 130, in <module>
    report.create()
  File "/home/prabhat/venvs/grimoirelab/lib/python3.6/site-packages/manuscripts/report.py", line 711, in create
    self.create_data_figs()
  File "/home/prabhat/venvs/grimoirelab/lib/python3.6/site-packages/manuscripts/report.py", line 603, in create_data_figs
    self.sections()[section]()
  File "/home/prabhat/venvs/grimoirelab/lib/python3.6/site-packages/manuscripts/report.py", line 267, in sec_overview
    (last, percentage) = m.get_trend()
  File "/home/prabhat/venvs/grimoirelab/lib/python3.6/site-packages/manuscripts/metrics/metrics.py", line 201, in get_trend
    ts = self.get_ts()
  File "/home/prabhat/venvs/grimoirelab/lib/python3.6/site-packages/manuscripts/metrics/metrics.py", line 150, in get_ts
    res = self.get_metrics_data(query)
  File "/home/prabhat/venvs/grimoirelab/lib/python3.6/site-packages/manuscripts/metrics/metrics.py", line 138, in get_metrics_data
    r.raise_for_status()
  File "/home/prabhat/venvs/grimoirelab/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 406 Client Error: Not Acceptable for url: http://localhost:9200/git_enrich/_search

This error arises because manuscript is trying to attempt a post request to wrong url (`http://localhost:9200/git_enrich/_search`)  . The enriched indexes will be successfully accessed by sending a post to `http://localhost:9200/git/_search`.

Temporarily for this particular problem I tried a workaround after cloning the manuscript code. All the things then worked successfully except the final pdf was not generated.
It required `pdfLatex` which I installed but then it asks for `Enter file name:` and when a name of file was entered in console then it shows errer: `! LaTeX Error: File `csvsimple.sty' not found`
In this case all the components like .tex , .png etc. files are present in `/tmp/reports` folder but final pdf couldn't be generated.

**Comment by f2014169** [comment]
@aswanipranjal  i think you can confirm this, as you were working on something related to this

**Comment by Prabhat-IIT** [comment]
Yup!! the first issue has been solved by the latest commit by @aswanipranjal . I see it after updating my local repo but still I think its not been included in the official realease. @f2014169  If you've any idea about the Latex issue please let me know :)

**Comment by aswanipranjal** [comment]
@Prabhat-IIT, i think you should update your local repo from chaoss/grimoirelab-manuscripts master branch and run Manuscripts from inside the updated repo. Regarding the error with Latex, I do not think Manuscripts asks for a name of the report. It just throws an error if it is not provided as an argument.

**Comment by Prabhat-IIT** [comment]
As stated above by me I've updated my local repo and the first bug has been removed. I would like to know more about the second bug regarding `pdfLatex`

**Comment by f2014169** [comment]
@Prabhat-IIT  please install this also
sudo apt-get install texlive-latex-extra
for complete support of pdflatex

**Comment by Prabhat-IIT** [comment]
@f2014169 didn't helped :(

**Comment by f2014169** [comment]
@Prabhat-IIT  download http://mirror.hmc.edu/ctan/macros/latex/contrib/csvsimple/csvsimple.sty
and when that asks for this file ,provide the location of this file, this works

**Comment by Prabhat-IIT** [comment]
Actually, this helped in generating the pdf partially i.e. some part of it can be made but ultimately it ends up in error. Thanks for helping btw :)
