### ISSUE TITLE
Change start_date from '2015-01-01' to the date of the first commit

### ISSUE THREAD

**Issue by aswanipranjal** [chaoss/grimoirelab-manuscripts#48]
Currently, the default start date is set to: 2015-01-01. [Link](https://github.com/chaoss/grimoirelab-manuscripts/blob/master/bin/manuscripts#L56)
Instead of using that hard coded value, we can change the start date of analysis to the date the first commit was made.

**Comment by jgbarah** [comment]
¿Anything new about this?

**Comment by aswanipranjal** [comment]
I wasn't able to look at it this past week. But I am hoping to work on it in this coming week.
