### ISSUE TITLE
Documentation on available sources and metrics

### ISSUE THREAD

**Issue by alpgarcia** [chaoss/grimoirelab-manuscripts#6]
Currently there is no explicit information on what sources and metrics are supported.

It can be done by directly updating README.md file. Probably it might be better to have this documented in source code and generate documentation from there. 

I have no experience with this kind of documentation in Python, so I would like to have your opinion @acs and @jgbarah beforehand.

**Comment by acs** [comment]
I would try generating the doc from source code, as you proposes. And if that is not possible, then move to the README.md approach.

**Comment by sduenas** [comment]
Not activity in more than a year. Closing it.
